In [7]:
import sys
import os
sys.path.insert(1, "~/Installations/MParT/python/")
os.environ['LD_LIBRARY_PATH']='~/Installations/MParT/lib/'

In [8]:
import numpy as np
import scipy 
import matplotlib.pyplot as plt
import scipy.stats
from scipy.stats import multivariate_normal
import time

In [9]:
np.eye(1)

array([[1.]])

In [13]:
std = np.random.randn(1,10)
mean =  np.random.randn(1,10)

In [22]:
mean.shape[1]

10

In [17]:
(std**2)*np.eye(len(mean))


array([[1.15729453e+00, 7.16794752e-01, 9.40330697e-04, 1.34338949e+00,
        2.43681388e+00, 1.84626592e-01, 3.49834781e-02, 3.08069225e-02,
        1.05941227e-02, 6.39227900e-01]])

In [20]:
mean

array([[-0.08578871,  0.06734404, -0.35982185,  1.3217532 , -0.35112027,
        -0.60676285,  0.90732252,  0.75827421, -0.68843248,  1.52195566]])

In [23]:
piZ0 = multivariate_normal(np.zeros((10,)),np.eye(10))

In [26]:
X=np.random.randn(10,100)

In [28]:
X[:1,:].shape

(1, 100)

In [ ]:
for i in range(2,5):
    print(i)

2
3
4
